        const quizSets = {
                        'Seed Plants': [
                { term: "Phloem", defs: ["The vascular tissue through which food moves.", "tissue that transports food in plants", "tubes that carry sugar throughout the plant"] },
                { term: "Xylem", defs: ["Vascular tissue through which water and minerals move.", "tissue that transports water in plants", "tubes that carry water from roots to leaves"] },
                { term: "Pollen", defs: ["Tiny structures that contain the cells that will later become sperm cells.", "male reproductive cells of plants", "powdery substance containing sperm cells"] },
                { term: "Seed", defs: ["A structure that contains a young plant inside a protective covering.", "protective structure containing a plant embryo", "plant's way of reproducing and spreading"] },
                { term: "Embryo", defs: ["The young plant that develops from the zygote, or fertilized egg.", "baby plant inside a seed", "developing plant within the seed"] },
                { term: "Cotyledons", defs: ["The part of the seed where food is stored.", "seed leaves that store food", "first leaves that provide nutrition for germination"] },
                { term: "Germination", defs: ["The process when the embryo grows and pushes out of the seed.", "when a seed begins to grow", "sprouting of a seed into a new plant"] },
                { term: "Root Cap", defs: ["Protects the root from injury as the root grows through the soil.", "protective covering at root tip", "structure that shields growing roots"] },
                { term: "Cambium", defs: ["A layer of cells which divide to produce new phloem and xylem.", "growth layer that produces new vascular tissue", "cells that make plants grow thicker"] },
                { term: "Stomata", defs: ["The small openings or pores on the surface of a leaf.", "pores on leaves for gas exchange", "tiny openings that control water loss"] },
                { term: "Transpiration", defs: ["The process in which water evaporates from a plant's leaves.", "water loss through leaf pores", "evaporation of water from plant surfaces"] },
                { term: "Gymnosperm", defs: ["A seed plant that produces naked seeds.", "plants with uncovered seeds", "cone-bearing plants like pine trees"] },
                { term: "Cone", defs: ["The reproductive structure of gymnosperms.", "seed-producing structure of conifers", "reproductive part of pine and fir trees"] },
                { term: "Ovule", defs: ["A structure that contains an egg cell.", "female reproductive structure in plants", "part of plant that develops into a seed"] },
                { term: "Pollination", defs: ["The transfer of pollen from the male reproductive structure to the female reproductive structure.", "movement of pollen to female parts", "process that allows plant fertilization"] },
                { term: "Angiosperm", defs: ["A flowering plant that produces seeds enclosed in a structure.", "flowering plants with protected seeds", "plants that produce flowers and fruits"] },
                { term: "Flower", defs: ["The reproductive structure of an angiosperm.", "plant part that produces seeds", "colorful structure for plant reproduction"] },
                { term: "Sepals", defs: ["Protect the developing flower.", "leaf-like structures that cover flower buds", "green parts that guard the flower"] },
                { term: "Petal", defs: ["The part of a flower that attracts pollinators.", "colorful flower part that attracts insects", "showy part of flower for attracting animals"] },
                { term: "Stamen", defs: ["The male reproductive part of a flower.", "pollen-producing part of flower", "male flower structure that makes pollen"] },
                { term: "Pistil", defs: ["The female reproductive part of a flower.", "egg-producing part of flower", "female flower structure that receives pollen"] },
                { term: "Ovary", defs: ["A hollow structure that protects the seeds as they develop.", "part of pistil that contains eggs", "structure that becomes the fruit"] },
                { term: "Fruit", defs: ["A ripened ovary and other structures that enclose one or more seeds.", "mature ovary containing seeds", "structure that protects and disperses seeds"] },
                { term: "Monocots", defs: ["Angiosperms with only one seed leaf.", "flowering plants with one cotyledon", "plants like grasses and lilies"] },
                { term: "Dicots", defs: ["Angiosperms with two seed leaves.", "flowering plants with two cotyledons", "plants like roses and oak trees"] },
                { term: "Tropism", defs: ["A plant's growth response toward or away from a stimulus.", "plant movement toward or away from stimuli", "directional growth response in plants"] },
                { term: "Hormone", defs: ["A chemical that affects how a plant grows and develops.", "chemical messenger that controls plant growth", "substance that regulates plant development"] },
                { term: "Auxin", defs: ["A plant hormone that speeds up the rate at which a plant's cells grow.", "hormone that promotes cell growth", "chemical that causes plant bending and growth"] },
                { term: "Photoperiodism", defs: ["A plant's response to seasonal changes in the length of night and day.", "plant response to day and night length", "how plants detect seasonal changes"] },
                { term: "Short-Day Plants", defs: ["Plants that flower when nights are longer than a critical length.", "plants that bloom in fall or winter", "plants that flower when days are short"] },
                { term: "Long-Day Plants", defs: ["Plants that flower when nights are shorter than a critical length.", "plants that bloom in spring or summer", "plants that flower when days are long"] },
                { term: "Critical Night Length", defs: ["The number of hours of darkness that determines whether or not a plant will flower.", "specific dark period needed for flowering", "darkness requirement for plant blooming"] },
                { term: "Day-Neutral Plants", defs: ["Plants whose flowering cycle is not sensitive to periods of light or dark.", "plants unaffected by day length", "plants that flower regardless of photoperiod"] },
                { term: "Dormancy", defs: ["A period when an organism's growth or activity stops.", "resting period with no growth", "inactive state during harsh conditions"] },
                { term: "Annuals", defs: ["Flowering plants that complete a life cycle within one growing season.", "plants that live for one year", "plants that grow, reproduce, and die in one season"] },
                { term: "Biennials", defs: ["Angiosperms that complete their life cycle in two years.", "plants that live for two years", "plants that flower in their second year"] },
                { term: "Perennials", defs: ["Flowering plants that live for more than two years.", "plants that live many years", "plants that return each growing season"] },
                { term: "Precision Farming", defs: ["A farming method in which farmers fine-tune the amount of water and fertilizer to match a specific field's requirements.", "farming using technology to optimize resources", "targeted farming based on specific field needs"] },
                { term: "Hydroponics", defs: ["A method of growing plants in solutions of nutrients instead of soil.", "growing plants without soil", "farming using nutrient-rich water solutions"] },
                { term: "Genetic Engineering", defs: ["A method where scientists alter an organism's genetic material to produce desired traits.", "changing an organism's DNA", "modifying genes to create new traits"] }
            ],
	        'Viruses and Bacteria': [
                { term: "Virus", defs: ["A tiny non-living particle that enters and then reproduces inside a living cell.", "non-living particle that reproduces inside cells", "infectious particle that needs a host cell"] },
                { term: "Host", defs: ["An organism that provides a source of energy for a virus or another organism.", "organism that provides energy for parasites", "living thing used by parasites"] },
                { term: "Parasite", defs: ["An organism that lives on or in a host and causes it harm.", "organism that harms its host", "organism that benefits while harming another"] },
                { term: "Bacteriophage", defs: ["A virus that infects bacteria.", "virus that attacks bacteria", "virus that destroys bacterial cells"] },
                { term: "Bacteria", defs: ["Single-celled organisms that lack a nucleus; Prokaryotes.", "single-celled organisms without a nucleus", "microscopic organisms without membrane-bound organelles"] },
                { term: "Cytoplasm", defs: ["The region inside the cell membrane, which contains a gel-like material.", "gel-like material inside the cell membrane", "watery substance that fills the cell"] },
                { term: "Ribosomes", defs: ["Chemical factories in the cytoplasm where proteins are produced.", "structures that make proteins", "protein-making organelles"] },
                { term: "Flagellum", defs: ["A long whip-like structure that helps a cell to move.", "whip-like structure for cell movement", "tail-like structure that propels cells"] },
                { term: "Respiration", defs: ["The process of breaking down food to release its energy.", "process that releases energy from food", "cellular process that produces energy"] },
                { term: "Binary Fission", defs: ["A form of reproduction in which one cell divides to form two identical cells.", "reproduction where one cell splits into two", "asexual reproduction by cell division"] },
                { term: "Asexual Reproduction", defs: ["A reproductive process that involves only one parent and produces offspring that are identical to the parent.", "reproduction involving only one parent", "reproduction that creates identical copies"] },
                { term: "Sexual Reproduction", defs: ["Involves two parents who combine their genetic material to produce a new organism, which differs from both parents.", "reproduction involving two parents", "reproduction that combines genetic material from two organisms"] },
                { term: "Conjugation", defs: ["One bacterium transfers some of its genetic material into another bacterium through a thin, thread-like bridge that joins the two cells.", "bacteria sharing genetic material through a bridge", "bacterial process of exchanging DNA"] },
                { term: "Endospore", defs: ["A small, rounded, thick-walled resting cell that forms inside a bacterial cell.", "protective resting cell formed by bacteria", "tough structure that helps bacteria survive harsh conditions"] },
                { term: "Pasteurization", defs: ["Food is heated to a temperature that is high enough to kill most harmful bacteria without changing the taste of the food.", "heating food to kill harmful bacteria", "heat treatment that makes food safer"] },
                { term: "Decomposers", defs: ["Organisms that break down large chemicals in dead organisms into small chemicals.", "organisms that break down dead material", "organisms that recycle nutrients from dead things"] },
                { term: "Infectious Diseases", defs: ["Illnesses that pass from one organism to another.", "diseases that spread between organisms", "diseases caused by pathogens"] },
                { term: "Toxin", defs: ["A poison that causes deadly diseases like tetanus.", "poison produced by bacteria", "harmful substance made by microorganisms"] },
                { term: "Antibiotic", defs: ["A chemical that can kill bacteria without harming a person's cells.", "medicine that kills bacteria", "drug used to treat bacterial infections"] },
                { term: "Antibiotic Resistance", defs: ["When some bacteria are able to survive the presence of an antibiotic.", "bacteria's ability to survive antibiotics", "when bacteria become immune to medicines"] },
                { term: "Vaccine", defs: ["A substance introduced into the body to stimulate the production of chemicals that destroy specific viruses or bacteria.", "substance that helps body fight specific diseases", "medicine that prevents infections by building immunity"] }
           ],
            "Cell Structure and Function": [
                                { term: "Cell", defs: ["The basic unit of structure and function of living things", "basic uint of structure and function in living things"] },
                { term: "Microscope", defs: ["An instrument that makes small things look larger", "instrument with lenses that magnifies small objects"] },
                { term: "Cell theory", defs: ["a widely accepted explanation of the relationship between cells and living things", "explanation of the relationship between cells and living things"] },
                { term: "Organelle", defs: ["Tiny cell structures that carry out specific functions within the cell", "membrane-bound structures of a cell"] },
                { term: "Cell Wall", defs: ["A rigid layer of nonliving material that surrounds the cells of plants and some other organisms", "non-living outer layer of plant cell"] },
                { term: "Cell membrane", defs: ["cell structure that controls which substances can enter or leave the cell", "structure which controls entry of materials into the cell"] },
                { term: "Nucleus", defs: ["The brain of the cell", "organelle which houses the DNA"] },
                { term: "Cytoplasm", defs: ["The region between the cell membrane and the nucleus", "region located inside the cell membrane"] },
                { term: "Mitochondria", defs: ["The 'powerhouse' of the cell because they convert energy in food molecules to energy the cell can use to carry out its functions", "organelle which produces energy for the cell"] },
                { term: "Endoplasmic Reticulum", defs: ["Passageways that carry proteins and other materials from one part of a cell to another", "cellular passageway for proteins"] },
                { term: "Ribosome", defs: ["Function as factories to produce proteins", "organelle where proteins are assembled"] },
                { term: "Golgi body", defs: ["The cell's mail room that distributes the materials", "packages and distributes materials within a cell"] },
                { term: "Chloroplast", defs: ["Capture energy from sunlight and use it to produce food for the cell", "organelle which captures light to produce glucose"] },
                { term: "Vacuole", defs: ["Storage areas for cells", "water filled sack within a cell"] },
                { term: "Lysosome", defs: ["Small round structure containing chemicals that break down certain materials in cells", "organelle which breaks down large molecules for the cell"] },
                { term: "Element", defs: ["Any substance that cannot be broken down into simpler substances", "substance that cannot be chemically broken down"] },
                { term: "Compound", defs: ["When two or more elements combine chemically", "two or more elements chemically combined"] },
                { term: "Carbohydrate", defs: ["An energy-rich organic compound made of the elements carbon, hydrogen, and oxygen", "sugars and starches"] },
                { term: "Lipids", defs: ["Energy-rich organic compounds made of carbon, hydrogen, and oxygen", "fats or oils"] },
                { term: "Proteins", defs: ["Large organic molecules made of carbon, hydrogen, oxygen, nitrogen, and in some cases sulfur", "organic compound of C, H, O, N"] },
                { term: "Amino acids", defs: ["Molecules smaller than protein molecules", "molecules that link to form proteins"] },
                { term: "Enzyme", defs: ["A type of protein that speeds up a chemical reaction in a living thing", "protein that speeds up a chemical reaction"] },
                { term: "Nucleic Acids", defs: ["Very long organic molecules made of carbon, oxygen, hydrogen, nitrogen, and phosphorus", "DNA and RNA"] },
                { term: "DNA", defs: ["The genetic material that carries info about an organism and is passed from parent to offspring", "deoxyribonucleic acid"] },
                { term: "RNA", defs: ["Plays an important role in production of proteins", "ribonucleic acid"] },
                { term: "Selectively Permeable", defs: ["Means that some substances can pass through the membrane while others cannot", "allowing only certain materials to pass through a membrane"] },
                { term: "Diffusion", defs: ["The process by which molecules move from an area of higher concentration to an area of lower concentration", "movement of particles from high to low concentration"] },
                { term: "Osmosis", defs: ["The diffusion of water molecules through a selectively permeable membrane", "diffusion of water through a membrane"] },
                { term: "Passive transport", defs: ["The movement of dissolved materials through a cell membrane without using cellular energy", "movement of materials through a cell membrane without using energy"] },
                { term: "Active transport", defs: ["The movement of materials through a cell membrane using cellular energy", "movement of materials through a cell membrane using energy"] }
            ],
            "Chapter 2": [
                {term: "autotroph", defs: ["an organism that is photosynthetic"]},
                {term: "heterotroph", defs: ["an organism that is not photosynthetic"]},
                {term: "cancer", defs: ["uncontrolled cell division resulting in a tumor"]},
                {term: "cell cycle", defs: ["six step process which includes mitosis"]},
                {term: "chemotherapy", defs: ["treatment of a cancerous tumor with medicine"]},
                {term: "chlorophyll", defs: ["green pigment found in autotrophs"]},
                {term: "chromosome", defs: ["coiled and x-shaped DNA molecule of mitosis"]},
                {term: "cytokinesis", defs: ["splitting of a cell into daughter cells"]},
                {term: "fermentation", defs: ["respiration which results in the production of alcohol"]},
                {term: "interphase", defs: ["first phase of the cell cycle"]},
                {term: "mitosis", defs: ["part of the cell cycle in which the DNA is distributed to daughter cells"]},
                {term: "mutation", defs: ["misread of the DNA or RNA which results in an improper protein"]},
                {term: "photosynthesis", defs:["process by which autotrophs produce oxygen and glucose"]},
                {term: "pigment", defs: ["light absorbing material which results in color expression"]},
                {term: "respiration", defs: ["process by which heterotrophs break down glucose"]},
                {term: "replication", defs: ["to duplicate a substance, such as a cell or DNA"]},
                {term: "stomata", defs: ["pore on the under side of a leaf for the exchange of air"]},
                {term: "tumor", defs: ["hard growth of tissue as a result of a cancer"]}
            ],
            "Cell Cycle": [
                {term: "prophase", defs: ["chromotin coils into chromosomes"]},
                {term: "telophase", defs: ["nuclear membrane (N membrane) reforms"]},
                {term: "prophase", defs: ["spindle migrates to the poles"]},
                {term: "interphase", defs: ["DNA uncoiled as chromatin"]},
                {term: "telophase", defs: ["Cell membrane begins to pinch in"]},
                {term: "anaphase", defs: ["chromosomes pull apart into chromotids"]},
                {term: "metaphase", defs: ["spindle aligns chromosomes at equator"]},
                {term: "prophase", defs: ["N membraine (nuclear membrane) breaks down"]},
                {term: "interphase", defs: ["N membrane (nuclear membrane) intact"]},
                {term: "telophase", defs: ["spindle breaks down"]},
                {term: "interphase", defs: ["DNA replicates itself from 2N to 4N"]},
                {term: "cytokinesis", defs: ["centrioles at rest"]},
                {term: "telophase", defs: ["chromotids uncoil back into chromatin"]},
                {term: "cytokinesis", defs: ["cell membrane pinches into two daughter cells"]},
            ],
            "The root GEN":[
                {term: "Congenial", defs: ["Having the same tastes, habits. Sociable; agreeable; amiable."]},
                {term: "Degenerate", defs: ["To sink into a much worse or lower condition; deteriorate."]},
                {term: "Gender", defs: ["One of the categories - masculine, feminine, or neuter - into which words and the people, animals, or objects they denote are divided."]},
                {term: "Genealogy", defs: ["A record of the descent of a family or person from an ancestor or ancestors. Direct descent from an ancestor; lineage. The study of ancestry and family histories."]},
                {term: "Generic", defs: ["Of, including, or indicating an entire group, class, category; general rather than specific. Not protected by a trademark."]},
                {term: "Genesis", defs: ["The coming into being of anything; origin."]},
                {term: "Gentry", defs: ["Well-bred people of good family and high social standing. A social class ranking next below the nobility."]},
                {term: "Primogeniture", defs: ["The condition of being the first-born child in a family. In law, the right of the eldest child - especially the eldest son - to inherit all of his parents' estate."]},
                {term: "Progeny", defs: ["Children; descendants; offspring"]},
                {term: "Regenerate", defs: ["To give a new life to; revive. To reform spiritually or morally. To replace by growing new tissue."]}
            ],
            "Families":[
                {term: "Descendant", defs: ["An individual or animal coming from a specific ancestor; offspring of a certain family or group."]},
                {term: "Generation", defs: ["All of the offspring that are at the same stage of descent from a common ancestor. A group of people who grow up at the same time and are thought to have similar ideas."]},
                {term: "Inheritance", defs: ["The act of receiving property or money after the death of a relative or friend. The property or money received at such a time. A characteristic, such as red hair, that is received genetically from a parent, grandparent, etc."]},
                {term: "Lineage", defs: ["Direct descent from a particular ancestor; ancestry. All of the descendants of a common ancestor."]},
                {term: "Maternal", defs: ["Referring to a mother or motherhood. Inherited from one's mother. Related to one's mother."]},
                {term: "Matriarch", defs: ["A woman who rules a family or clan."]},
                {term: "Paternal", defs: ["Characteristic of a mother or father."]},
                {term: "Patriarch", defs: ["The male leader of a family or clan."]},
                {term: "Posterity", defs: ["Future generations. All of persons descendants."]},
                {term: "Sibling", defs: ["One of two or more children of the same parents; a brother or a sister."]}
            ],
            "Happiness and unhappiness":[
                {term: "Amicable", defs: ["Friendly in tone."]},
                {term: "Anguish", defs: ["Great physical or mental pain; torment; torture. To suffer greatly."]},
                {term: "Blithe", defs: ["Cheerful; carefree; lighthearted."]},
                {term: "Defiant", defs: ["Openly or boldly resisting authority."]},
                {term: "Desolate", defs: ["Lonely and sad; wretched; forlorn. Having little or no vegetation; barren. Having few or no inhabitants; deserted."]},
                {term: "Despondent", defs: ["In low spirits; depressed; dejected."]},
                {term: "Disgruntled", defs: ["Discontented or cross."]},
                {term: "Disillusion", defs: ["To free or deprive of an idea or belief that proves false or in error; disenchant."]},
                {term: "Distress", defs: ["Anxiety, discomfort, or suffering; worry."]},
                {term: "Exuberant", defs: ["Lively and joyous; enthusiastic; high-spirited."]}
            ],
	    "Genetics: The Science of Heredity":[
		{term: "alleles", defs: ["different forms of a gene"]},
		{term: "codominance", defs:["allele that is not dominant or recessive"]},
		{term: "dominant allele", defs:["allele whose trait is always expressed when present"]},
		{term: "fertilization", defs: ["process in which the egg and sperm cell join"]},
		{term: "gene", defs: ["segment of DNA that codes for a specific trait"]},
		{term: "genetics", defs:["scientific study of heredity"]},
		{term: "genotype", defs:["organism's allele combination"]},
		{term: "heredity", defs:["passing of traits from parents to offspring"]},
		{term: "heterozygous", defs:["having two different alleles for a trait"]},
		{term: "homozygous", defs:["having two identical alleles for a trait"]},
		{term: "hybrid", defs:["organism that is heterozygous for a trait"]},
		{term: "meiosis", defs:["reduction of a chromosome by half"]},
		{term: "messenger RNA", defs:["RNA that copes a code of DNA"]},
		{term: "phenotype", defs:["organism's physical appearance"]},
		{term: "probability", defs:["likelihood that an event will occur"]},
		{term: "Punnett square", defs:["chart showing the possible alleles from a genetic cross"]},
		{term: "purebred", defs:["organism producing offspring with the same traits as the parent"]},
		{term: "recessive allele", defs:["allele that is masked by a dominant allele"]},
		{term: "trait", defs:["characteristic an organism passes on to its offspring"]},
		{term: "transfer RNA", defs:["RNA that carries the amino acid to the ribosome"]}
	    ],
        "Cardiovascular System": [
            {term: "Cardiovascular system", defs: ["The body system that consists of the heart, blood vessels, and blood"]},
            {term: "Heart", defs: ["A hollow, muscular organ that pumps blood throughout the body"]},
            {term: "Atrium", defs: ["Each of the two upper chambers of the heart that receives blood that comes in to the heart"]},
            {term: "Ventricle", defs: ["Each of the two lower chambers of the heart that pumps blood out of the heart"]},
            {term: "Valve", defs: ["A flap of tissue in the heart or a vein that prevents blood from flowing backward"]},
            {term: "Pacemaker", defs: ["A group of cells located in the right atrium that sends out signals that makes the heart muscle contract and that regulates heart rate"]},
            {term: "Artery", defs: ["A blood vessel that carries blood away from the heart"]},
            {term: "Capillary", defs: ["A tiny blood vessel where substances are exchanged between the blood and the body cells"]},
            {term: "Vein", defs: ["A blood vessel that carries blood back to the heart"]},
            {term: "Aorta", defs: ["The largest artery in the body"]},
            {term: "Coronary artery", defs: ["An artery that supplies blood to the heart itself"]},
            {term: "Pulse", defs: ["The alternating expansion and relaxation of an artery wall as blood travels through an artery"]},
            {term: "Diffusion", defs: ["The process by which molecules move from an area of higher concentration to an area of lower concentration"]},
            {term: "Blood Pressure", defs: ["The pressure that is exerted by the blood against the wall of blood vessels"]},
            {term: "Plasma", defs: ["The liquid part of blood"]},
            {term: "Red blood cell", defs: ["A cell in the blood that takes up oxygen in the lungs and delivers it to cells elsewhere in the body"]},
            {term: "Hemoglobin", defs: ["An iron-containing protein that binds chemically to oxygen molecules"]},
            {term: "White blood cell", defs: ["A blood cell that fights disease"]},
            {term: "Platelet", defs: ["A cell fragment that plays an important part in forming blood clots"]},
            {term: "Lymphatic System", defs: ["A network of veinlike vessels that returns the fluid that leaks out of blood vessels to the bloodstream"]},
            {term: "Lymph", defs: ["The fluid that the lymphatic system collects and returns to the bloodstream"]},
            {term: "Lymph node", defs: ["A small knob of tissue in the lymphatic system that filters lymph, trapping bacteria and other microorganisms that cause disease"]},
            {term: "Atherosclerosis", defs: ["A condition in which an artery wall thickens, as a result of the buildup of fatty materials"]},
            {term: "Hypertension", defs: ["A disorder in which a person's blood pressure is constantly higher than normal"]},
            {term: "Heart Attack", defs: ["A condition in which blood flow to part of the heart muscle is blocked causing heart cells to die"]}
        ],
        "Respiration and Excretion": [
            {term: "respiration", defs: ["the process in which oxygen and glucose undergo a complex series of chemical reactions inside cells"]},
            {term: "cilia", defs: ["tiny hairlike extensions that move together in a sweeping motion"]},
            {term: "pharynx", defs: ["the throat"]},
            {term: "trachea", defs: ["the windpipe"]},
            {term: "bronchi", defs: ["the passages that direct air into the lungs"]},
            {term: "lungs", defs: ["the main organs of the respiratory system"]},
            {term: "alveoli", defs: ["tiny sacs of lung tissue specialized for the movement of gases between air and blood"]},
            {term: "diaphragm", defs: ["a large dome-shaped muscle that plays an important role in breathing"]},
            {term: "larynx", defs: ["the voice box"]},
            {term: "vocal cords", defs: ["folds of connective tissue that stretch across the opening of the larynx and produce a person's voice"]},
            {term: "tar", defs: ["a dark, sticky substance that forms when tobacco burns"]},
            {term: "carbon monoxide", defs: ["a colorless, odorless gas produced when substances, including tobacco, are burned"]},
            {term: "nicotine", defs: ["a stimulant drug in tobacco that increases the activities of the nervous system, heart, and other organs"]},
            {term: "addiction", defs: ["a physical dependence on a substance"]},
            {term: "bronchitis", defs: ["an irritation of the breathing passages in which the small passages become narrower than normal and may be clogged with mucus"]},
            {term: "emphysema", defs: ["a serious disease that destroys lung tissue and causes breathing difficulties"]},
            {term: "excretion", defs: ["the process by which wastes are removed from the body"]},
            {term: "urea", defs: ["a chemical that comes from the breakdown of proteins"]},
            {term: "kidney", defs: ["a major organ of the excretory system which removes urea and other wastes from the blood"]},
            {term: "urine", defs: ["a watery fluid produced by the kidneys that contains urea and other wastes"]},
            {term: "ureter", defs: ["a narrow tube that carries urine from one of the kidneys to the urinary bladder"]},
            {term: "urinary bladder", defs: ["a sacklike muscular organ that stores urine until it is eliminated from the body"]},
            {term: "urethra", defs: ["a small tube through which urine flows from the body"]},
            {term: "nephron", defs: ["small filtering structure found in the kidneys that removes wastes from blood and produces urine"]}
        ]
        };

